[2024-01-21T23:29:30.811+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion.load_data manual__2024-01-21T23:29:26.946086+00:00 [queued]>
[2024-01-21T23:29:30.814+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion.load_data manual__2024-01-21T23:29:26.946086+00:00 [queued]>
[2024-01-21T23:29:30.814+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-01-21T23:29:30.819+0000] {taskinstance.py:1382} INFO - Executing <Task(_PythonDecoratedOperator): load_data> on 2024-01-21 23:29:26.946086+00:00
[2024-01-21T23:29:30.822+0000] {standard_task_runner.py:57} INFO - Started process 3504 to run task
[2024-01-21T23:29:30.824+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion', 'load_data', 'manual__2024-01-21T23:29:26.946086+00:00', '--job-id', '345', '--raw', '--subdir', 'DAGS_FOLDER/fetch-api-data.py', '--cfg-path', '/tmp/tmpu9u592i0']
[2024-01-21T23:29:30.825+0000] {standard_task_runner.py:85} INFO - Job 345: Subtask load_data
[2024-01-21T23:29:30.843+0000] {task_command.py:416} INFO - Running <TaskInstance: data_ingestion.load_data manual__2024-01-21T23:29:26.946086+00:00 [running]> on host 913a57d7b377
[2024-01-21T23:29:30.937+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-01-21T23:29:26.946086+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-21T23:29:26.946086+00:00'
[2024-01-21T23:29:30.940+0000] {logging_mixin.py:154} INFO - connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-01-21T23:29:30.941+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-01-21T23:29:30.946+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=data_ingestion, task_id=load_data, execution_date=20240121T232926, start_date=20240121T232930, end_date=20240121T232930
[2024-01-21T23:29:30.999+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-01-21T23:29:31.008+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
