[2024-03-26T15:30:37.232+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion.load_data scheduled__2024-03-25T09:00:00+00:00 [queued]>
[2024-03-26T15:30:37.236+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion.load_data scheduled__2024-03-25T09:00:00+00:00 [queued]>
[2024-03-26T15:30:37.237+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-03-26T15:30:37.242+0000] {taskinstance.py:1382} INFO - Executing <Task(_PythonDecoratedOperator): load_data> on 2024-03-25 09:00:00+00:00
[2024-03-26T15:30:37.249+0000] {standard_task_runner.py:57} INFO - Started process 367 to run task
[2024-03-26T15:30:37.253+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion', 'load_data', 'scheduled__2024-03-25T09:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/fetch-api-data.py', '--cfg-path', '/tmp/tmpkzpgvxr4']
[2024-03-26T15:30:37.256+0000] {standard_task_runner.py:85} INFO - Job 8: Subtask load_data
[2024-03-26T15:30:37.308+0000] {task_command.py:416} INFO - Running <TaskInstance: data_ingestion.load_data scheduled__2024-03-25T09:00:00+00:00 [running]> on host 59861fdcda9f
[2024-03-26T15:30:37.453+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-03-25T09:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-25T09:00:00+00:00'
[2024-03-26T15:30:37.462+0000] {logging_mixin.py:154} INFO - Error while connecting to PostgreSQL The conn_id `postgres_conn` isn't defined
[2024-03-26T15:30:37.463+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-03-26T15:30:37.467+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=data_ingestion, task_id=load_data, execution_date=20240325T090000, start_date=20240326T153037, end_date=20240326T153037
[2024-03-26T15:30:37.514+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-03-26T15:30:37.533+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-26T16:13:35.383+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion.load_data scheduled__2024-03-25T09:00:00+00:00 [queued]>
[2024-03-26T16:13:35.388+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion.load_data scheduled__2024-03-25T09:00:00+00:00 [queued]>
[2024-03-26T16:13:35.389+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-03-26T16:13:35.395+0000] {taskinstance.py:1382} INFO - Executing <Task(_PythonDecoratedOperator): load_data> on 2024-03-25 09:00:00+00:00
[2024-03-26T16:13:35.399+0000] {standard_task_runner.py:57} INFO - Started process 526 to run task
[2024-03-26T16:13:35.401+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion', 'load_data', 'scheduled__2024-03-25T09:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/fetch-api-data.py', '--cfg-path', '/tmp/tmp4s25rc_6']
[2024-03-26T16:13:35.403+0000] {standard_task_runner.py:85} INFO - Job 8: Subtask load_data
[2024-03-26T16:13:35.429+0000] {task_command.py:416} INFO - Running <TaskInstance: data_ingestion.load_data scheduled__2024-03-25T09:00:00+00:00 [running]> on host b3a14f9969c8
[2024-03-26T16:13:35.523+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-03-25T09:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-25T09:00:00+00:00'
[2024-03-26T16:13:35.528+0000] {base.py:73} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-03-26T16:13:35.539+0000] {logging_mixin.py:154} INFO - Data inserted successfully
[2024-03-26T16:13:35.539+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-03-26T16:13:35.546+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=data_ingestion, task_id=load_data, execution_date=20240325T090000, start_date=20240326T161335, end_date=20240326T161335
[2024-03-26T16:13:35.582+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-03-26T16:13:35.596+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
